
[
build-system
]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[
project
]
name = "particle-simulator"
version = "0.1.0"
description = "Particle physics simulation package"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "taichi",
    "numpy",
]
